import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import "assets/styles/font.css";
import "assets/styles/checkbox.css";
import "assets/styles/toast.css";
import { Inter } from "next/font/google";
import DefaultContainer from "components/defaultContainer";
import ReactQueryProvider from "../queries/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultContainer>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </DefaultContainer>

        <ToastContainer position="bottom-center" hideProgressBar />
      </body>
    </html>
  );
}
