name: Deploy # Workflow 이름
on: # Event 감지
  push:
    branches: 
      - chore/github-action-test#3
env:
  CI: false
  S3_BUCKET_NAME: ddd-rainbow-bucket
  CODE_DEPLOY_APPLICATION_NAME: github-action
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: github-action-group
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2
      - name: Check Node v # Node v 확인
        run: node -v
      - name: Install Dependencies # 의존 파일 설치
        run: npm ci
      - name: Build # React Build
        run: npm run build
      - name: zip create 
# zip 파일을 만듭니다(파일명은 자유, 대신 아래 workflow에 적을 파일명과 동일하게 맞춰주세요).
        run: zip -qq -r ./**build-fe.zip .**
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 **./build-fe.zip** s3://${{ env.S3_BUCKET_NAME }}/**build-fe.zip**
      - name: Deploy # Deploy to EC2
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{ env.S3_BUCKET_NAME }},bundleType=zip,key=$GITHUB_SHA.zip
